module.exports={
    devServer:{
        proxy:{
            '/api':{
                target:"https://api.binstd.com",
                changeOrigin:true,
                pathRewrite:{
                    "^/api":"https://api.binstd.com"
                }
            },
        }
    }
}
